durableverse: main.o carte.o plateau.o interface.o game.o structure.o
	gcc -o durableverse -Wall $^

structure.o: structure.c
	gcc -c $<

main.o: main.c
	gcc -c $<

game.o: game.c
	gcc -c $<

carte.o: carte.c
	gcc -c $<

plateau.o: plateau.c
	gcc -c $<

interface.o: interface.c
	gcc -c $<

